app:
    image: ubuntu:14.04
    volumes:
        - ./source:/var/www/
    tty: true

nginx:
    build: dockers/nginx/prod
    ports:
        - 80:80
    links:
        - php
    tty: true
    volumes_from:
        - app

php:
    build: dockers/php/prod
    expose:
        - 9000
    environment:
        - SYMFONY_ENV=prod
    volumes_from:
        - app
    tty: true
    links:
        - database

database:
    build: dockers/mysql/prod
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/backups:/tmp/backups
    ports:
        - 3306:3306
    tty: true

nodejs:
    build: dockers/nodejs
    volumes_from:
        - app
    tty: true
