MyAssistant\AuthJwtBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        username:
            expose: true
            type: string
        email:
            expose: true
            type: string
        timezone:
            expose: true
            type: string
