CREATE USER 'site_admin'@'%' IDENTIFIED BY 'secretpwd';

CREATE DATABASE IF NOT EXISTS `site` CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON `site`.* TO `site_admin`;

DROP DATABASE IF EXISTS test