security:
    encoders:
        default_encoder:
            algorithm: bcrypt
            cost: 15
    providers:
        db_provider:
            entity:
                class: MyAssistantAuthJwtBundle:User
    firewalls:
        api_documentation:
            pattern: ^/api/doc
            security: false
        user_creation:
            pattern: ^/api/v1/users/registration$
            methods: [POST]
            security: false
        confirm_email:
            pattern: ^/api/v1/email/[^/]+/confirm/[^/]+$
            methods: [DELETE]
            security: false
        resend_confirm:
            pattern: ^/api/v1/email/[^/]+/resend_confirmation_code$
            methods: PUT
            security: false
        gettoken:
            pattern:  ^/api/v1/get_token$
            stateless: true
            gfreeau_get_jwt:
                # this is the default config
                username_parameter: username
                password_parameter: password
                post_only: true
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                throw_exceptions: true
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~

#    access_control:
#        - { path: ^/api/v1/users/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }